language: go

go:
  - "1.11.x"

env:
  - DEP_VERSION="0.5.0"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

notifications:
  email: false

before_script:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  # code checkers/linters
  - golangci-lint run
  # race detector
  - go test -v -race ./...
  # static analyzer
  - go vet ./...
